version: '2'

services:
  app:
    image: 'socketchat-app:latest'
    container_name: socketchat-app
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - REDIS_URL=redis://cache:6379
    depends_on:
      - cache

  cache:
    image: 'redis:6.2'
    container_name: redis
